name: Generate GitHub Streak

on:
  schedule:
    - cron: '0 0 * * *'   # update tiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  generate-streak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install streak-stats CLI
        run: |
          npm install -g github-readme-streak-stats

      - name: Generate streak SVG
        run: |
          streak-stats --user diigel --theme blue-navy --hide-border true --output profile/streak.svg

      - name: Commit and push SVG
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak.svg"
          git push
